### ISSUE TITLE
problem with doesPasscodeExist function

### ISSUE THREAD

**Issue by skrosoft** [rolandleth/LTHPasscodeViewController#166]
Hello @rolandleth 

The function `doesPasscodeExist` actually return true if there is at least one passcode on the phone.

This function should receive opcionally parameters `username` and `servicename`, or use the current data setted with:

```
LTHPasscodeViewController.sharedUser().keychainPasscodeUsername = "user232"
LTHPasscodeViewController.sharedUser().keychainServiceName = "myServiceName"
```

It doesnt work for me with multiple users.

Vincent

**Comment by rolandleth** [comment]
Hey,


It doesn't receive a param, because it wasn't thought of having multiple users when it was created, but calling those setters should work (even just the username), because internally it asks for the passcode based on those properties. 

I guess it could be improved by taking them as parameters, to improve the process a bit.

**Comment by skrosoft** [comment]
You're right, it works, i forgot to remove this line:

`LTHPasscodeViewController.useKeychain(false)`

Thanks,
