### ISSUE TITLE
Keyboard behind viewcontroller when launched app launched from local notification

### ISSUE THREAD

**Issue by cswelin** [rolandleth/LTHPasscodeViewController#64]
When launching an app from a UILocationNotification the keyboard is missing or behind the controller..

Can be reproduced by firign a local notification and launching the app via the notification.

**Comment by ivdma** [comment]
This happens to me even without notification. When I press on the app icon, lock screen appears without the keyboard.

**Comment by rolandleth** [comment]
On a real device too? Because I had this problem on the simulator, but on a device it was working properly.

**Comment by ivdma** [comment]
Yeah, real device has this too. I had this on the simulator first, but appeared to be a problem with Hardware Keyboard being connected. It happens when app starts for the first time. After home button is pressed and app icon tapped, keyboard appears again.

Could it be me calling `- showLockScreenWithAnimation(etc)` from `application: application didFinishLaunchingWithOptions: options`? i.e.: should I call it from initial view controller?

**Comment by rolandleth** [comment]
You can try to call it still from there, but after you init and set your `rootViewController`. If it still doesn't work, try it as you said, from your main `viewController` and let me know, please; I will look at it, but I'm currently on a trip.

**Comment by ivdma** [comment]
I've tried to call passcode in app delegate after the rootViewController was instantiated and window made key and visible. Still no keyboard first time. Now I've put lock screen into root view controller and it works fine. Thanks for your answers. Have a nice trip!

**Comment by rolandleth** [comment]
Good to hear! Thanks :)

**Comment by 511430** [comment]
I had the same issue, I tried calling the ```showLockScreenWithAnimation()``` from my navigation controller instead of my AppDelegate, this still didn't work, but I have found a solution.
The solution was to call the method from the main thread which works perfectly!

**Comment by rolandleth** [comment]
Judging by the last 2 comments, I guess I can close this issue, right?
